import type { Glossary } from "./types";

export const GLOSSARY: Glossary = {
  inflation: "The slow rise in prices over time, which means the same €1 buys a little less each year.",
  compounding: "When your returns start earning their own returns, so growth stacks on growth the longer you stay invested.",
  volatility: "The normal up-and-down bouncing of prices. Temporary, it only becomes a real loss if you sell into it.",
  "permanent loss": "Money that does not come back, e.g. a company going bankrupt or panic-selling at the bottom.",
  "time horizon": 'How long until you actually need the money. It changes what "safe" means for you.',
  share: "A tiny slice of ownership in a single company.",
  bond: "Essentially a loan to a government or company that pays you interest.",
  fund: "A basket that spreads your money across many investments at once.",
  ETF: "A fund you can buy and sell like a share, usually low-cost.",
  "index fund": "A fund that simply mirrors a whole market instead of paying someone to pick winners.",
  diversification: "Spreading money across many holdings so no single failure can sink you.",
  "expense ratio": "The yearly fee a fund charges, shown as a percentage of what you hold.",
  broker: "A platform that lets you buy funds and shares yourself: lowest cost, most control.",
  "robo-advisor": "A service that builds and manages a portfolio for you automatically, for a slightly higher fee.",
  KYC: '"Know Your Customer", the ID check a regulated platform runs before you can invest.',
  "market order": "An order that buys now at the current price.",
  "limit order": "An order that only buys at a price you set.",
  blockchain: "A shared digital ledger copied across many computers, with no single owner, where past entries are very hard to change.",
  cryptocurrency: "A digital asset that lives on a blockchain; unlike a share it usually has no business or cash flows behind it.",
  stablecoin: "A crypto-asset that tries to hold a steady value, often pegged to a currency.",
  custodial: "When an exchange holds your crypto for you: convenient, but you are trusting that platform.",
  "self-custody": "When you hold your own keys: full control, and full responsibility.",
  "recovery phrase": "The secret word list that restores a self-custody wallet. Anyone who has it controls the funds, never share it.",
  MiCA: "The EU's Markets in Crypto-Assets regulation; a licensed platform under it is a regulated CASP.",
  "dollar-cost averaging": "Investing a fixed amount on a regular schedule, automatically, whatever the price.",
  rebalancing: "Occasionally trimming what has grown too big so your risk stays where you intended.",
  "core and satellite": "A boring diversified core doing the long-term work, plus a small bounded satellite for engagement.",
  "emergency fund": "Roughly 3–6 months of essential expenses in a plain savings account, so surprises never force you to sell investments.",
  "pay yourself first": "Moving a fixed amount to savings or investing on payday, before you can spend it.",
  "standing order": "An automatic bank transfer on a schedule, one good decision that replaces monthly willpower.",
  "loss aversion": "Losses feel roughly twice as strong as equal gains, the wiring behind panic-selling.",
  FOMO: "Fear of missing out: the manufactured feeling that everyone is getting rich without you.",
  "survivorship bias": "You only see the winners who post; the quiet losers make the odds look far better than they are.",
  anchoring: "Treating a meaningless old number (like a past price) as if it says something about value today.",
  overconfidence: "Mistaking a lucky win for skill, right before the bigger bet that gives it back.",
  "pump and dump": "Organisers hype an asset they already own, then sell into the buying they created.",
  "savings rate": "The share of your income you keep, the strongest lever you fully control on the road to FI.",
  "financial independence": "The point where investments could cover your living costs, making work a choice.",
  "4% rule": "A rough compass from old US data: a pot of ~25× yearly spending survived most historical 30-year retirements.",
  "FI number": "Roughly 25× your yearly spending, the ballpark pot where work becomes optional.",
  "Coast FI": "Having invested enough, early enough, that compounding alone should reach a retirement pot by normal retirement age.",
  "sequence of returns": "The order of good and bad years, a crash early in retirement hurts far more than one later.",
  REIT: "A company owning income-producing property whose shares trade like a stock, real estate without the tenants.",
  leverage: "Investing with borrowed money, like a mortgage, it amplifies gains and losses alike.",
  liquidity: "How quickly something converts to cash at a fair price. Shares: seconds. A house: months.",
  tilt: "A deliberate overweight of one sector or theme on top of a diversified core, sized so it can't sink the plan.",
  "hardware wallet": "A dedicated device keeping crypto keys off your internet-connected computer.",
  slashing: "A penalty on proof-of-stake networks that can trim a validator's staked coins.",
  staking: "Locking coins to help run a proof-of-stake network in exchange for protocol rewards, paid in the same volatile asset.",
  "smart contract": "A program on a blockchain that executes automatically, no bank, but also no undo button.",
  DeFi: "Financial plumbing (trading, lending) run by smart contracts instead of institutions. Novel, and unforgiving.",
  "rug pull": "The team behind a crypto project drains the funds and disappears.",
  "approval drain": "A malicious on-chain permission that quietly lets a contract spend your tokens later.",
  "phishing": "Fake sites or messages built to make you type in credentials or a recovery phrase.",
  CASP: "A crypto-asset service provider licensed under MiCA, the only kind of platform we ever reference.",
  "national regulator": "Every EU country has a financial-conduct watchdog, coordinated at EU level by ESMA: AFM (Netherlands), BaFin (Germany), CNMV (Spain), CMVM (Portugal).",
  ESMA: "The EU's securities-markets authority. It coordinates national regulators and keeps the public register of MiCA-licensed crypto platforms.",
  "compensation scheme": "Protection that may cover cash or assets if a regulated firm fails. Crypto generally has none.",
  dividend: "A share of profits a company pays out to its shareholders.",
  "fractional shares": "Buying a slice of a share, so small monthly amounts still diversify properly.",
  "market cap": "Price × number of shares (or coins), what the market says the whole thing is worth.",
  "bear market": "A drop of 20%+ from a peak. Normal, recurring, and survivable for diversified long-term investors.",
  "bull market": "A sustained rise in prices, pleasant, and the breeding ground for overconfidence.",
  KID: "The Key Information Document every EU fund must hand you before you buy: risk score 1–7, performance scenarios, costs over time.",
  UCITS: "The EU regulatory standard for retail funds: diversification and custody rules built in. Most flagship EU ETFs carry it in the name.",
  TER: "Total expense ratio, the fund's yearly fee. The single most comparable number on a factsheet.",
  "accumulating ETF": "Reinvests dividends automatically inside the fund. A distributing ETF pays them out to you instead.",
  "withholding tax": "The slice a country takes from dividends before they reach your fund, which is why most UCITS ETFs are Irish-domiciled (15% on US dividends instead of 30%).",
  segregation: "Client investments held apart from a broker's own assets; if the broker fails, your holdings are still yours.",
  "deposit guarantee scheme": "EU protection for bank deposits up to €100,000 per person per bank.",
  "investor compensation scheme": "EU floor of at least €20,000 per person per firm when a failed firm's client assets go missing. Never covers ordinary market losses.",
  CFD: "Contract for difference, a leveraged bet on a price move where you never own the asset. EU platforms must disclose that most retail accounts lose money.",
  "margin call": "A forced close-out when a leveraged position's losses approach your stake, often locking in the loss right before a recovery.",
  "pension gap": "The difference between the state pension you're projected to get and what your life actually costs, the number long-term investing exists to close.",
  PEPP: "The pan-European personal pension, an EU pillar-3 wrapper designed to stay portable when you move between countries.",
  "hot wallet": "Crypto keys on an internet-connected device, convenient, always an attack surface. For spending amounts.",
  "cold wallet": "Crypto keys kept offline (hardware wallet, paper), the safer home for anything meaningful.",
  "gas fee": "The network fee paid for a crypto transaction. Swings with congestion, sometimes cents, sometimes painful.",
  "test send": "Sending a small amount first and confirming it arrives before moving the rest. Crypto transfers are irreversible; this is the cheapest insurance there is.",
  "proof of work": "Consensus by burning energy: miners race to solve costly puzzles, and that cost is the security. Bitcoin's model.",
  "proof of stake": "Consensus by locked collateral: validators stake their own coins and get slashed for cheating. Ethereum's model since 2022 (~99.9% less energy).",
  halving: "Bitcoin's scheduled cut of new-coin supply, roughly every four years. Designed scarcity, which makes it limited, not automatically valuable.",
  CBDC: "Central bank digital currency, digital money issued by a central bank itself (like the ECB's planned digital euro), with no private issuer that can go bust.",
  drawdown: "The fall from a peak to a low. Long-term investing means sitting through many; only selling turns one into a permanent loss.",
  "currency risk": "The exchange-rate layer of a foreign investment's return, a world ETF is ~60–70% dollar assets, so EUR/USD sometimes writes your yearly result.",
  "hedged share class": "A fund version that cancels currency swings using contracts, for an ongoing cost. 'EUR Hedged' appears in the name.",
  "copy trading": "Your account automatically mirrors another trader's moves. Leaders usually earn from follower volume, not follower profits.",
  finfluencer: "Someone giving financial content on social media. A referral code is a payment; personal recommendations require a licence you can check in your national register.",
  deepfake: "AI-generated video or audio of a real person saying things they never said. Cheap to make, hard to spot by eye, which is why claims get verified at the source, not by watching closely.",
  "prediction market": "A platform for all-or-nothing bets on events (elections, matches, decisions). Looks like investing, pays like betting; ESMA says binary-payout contracts can fall under the EU's retail binary-options ban.",
  "wind-down": "The orderly shutdown of a financial firm's services, clients are notified and given time to withdraw or transfer assets. Real wind-down notices never ask for passwords or recovery phrases.",
};
