import type { Glossary } from "./types";

export const GLOSSARY: Glossary = {
  inflation: "The slow rise in prices over time, which means the same €1 buys a little less each year.",
  compounding: "When your returns start earning their own returns, so growth stacks on growth the longer you stay invested.",
  volatility: "The normal up-and-down bouncing of prices. Temporary — it only becomes a real loss if you sell into it.",
  "permanent loss": "Money that does not come back, e.g. a company going bankrupt or panic-selling at the bottom.",
  "time horizon": 'How long until you actually need the money. It changes what "safe" means for you.',
  share: "A tiny slice of ownership in a single company.",
  bond: "Essentially a loan to a government or company that pays you interest.",
  fund: "A basket that spreads your money across many investments at once.",
  ETF: "A fund you can buy and sell like a share, usually low-cost.",
  "index fund": "A fund that simply mirrors a whole market instead of paying someone to pick winners.",
  diversification: "Spreading money across many holdings so no single failure can sink you.",
  "expense ratio": "The yearly fee a fund charges, shown as a percentage of what you hold.",
  broker: "A platform that lets you buy funds and shares yourself — lowest cost, most control.",
  "robo-advisor": "A service that builds and manages a portfolio for you automatically, for a slightly higher fee.",
  KYC: '"Know Your Customer" — the ID check a regulated platform runs before you can invest.',
  "market order": "An order that buys now at the current price.",
  "limit order": "An order that only buys at a price you set.",
  blockchain: "A shared digital ledger copied across many computers, with no single owner, where past entries are very hard to change.",
  cryptocurrency: "A digital asset that lives on a blockchain; unlike a share it usually has no business or cash flows behind it.",
  stablecoin: "A crypto-asset that tries to hold a steady value, often pegged to a currency.",
  custodial: "When an exchange holds your crypto for you — convenient, but you are trusting that platform.",
  "self-custody": "When you hold your own keys — full control, and full responsibility.",
  "recovery phrase": "The secret word list that restores a self-custody wallet. Anyone who has it controls the funds — never share it.",
  MiCA: "The EU's Markets in Crypto-Assets regulation; a licensed platform under it is a regulated CASP.",
  "dollar-cost averaging": "Investing a fixed amount on a regular schedule, automatically, whatever the price.",
  rebalancing: "Occasionally trimming what has grown too big so your risk stays where you intended.",
  "core and satellite": "A boring diversified core doing the long-term work, plus a small bounded satellite for engagement.",
};
