import type { ScamScenario } from "./types";

// Scam-spotting scenarios — teaches Lesson 7 red flags, names no real assets.
export const SCAM_SCENARIOS: ScamScenario[] = [
  {
    id: "s1",
    channel: "DM",
    from: "Wallet Support",
    isScam: true,
    body: "⚠️ Your wallet flagged unusual activity. To secure it, verify your 12-word recovery phrase at wallet-verify-secure.net within 30 minutes or access will be locked.",
    why: "No real service ever needs your recovery phrase — it IS your wallet. Urgency + a look-alike link are classic theft.",
    flags: ["Asks for your recovery phrase", "Manufactured 30-minute urgency", 'Look-alike "verify" domain'],
  },
  {
    id: "s2",
    channel: "email",
    from: "ETF Broker",
    isScam: false,
    body: "Your monthly statement is ready. Log in at your broker directly to view it. We will never ask for your password or 2FA code by email.",
    why: "Neutral, no urgency, asks for nothing, and tells you to navigate to the site yourself. That is how legitimate messages read.",
    flags: [],
  },
  {
    id: "s3",
    channel: "DM",
    from: "CryptoKing_Signals",
    isScam: true,
    body: "Send 0.1 ETH to this address and get 0.5 ETH back — guaranteed, today only. First 100 people. My followers are already 5x up. DM me GO.",
    why: '"Send money, get more back guaranteed" is always a scam. No one gives away free returns; guaranteed multiples do not exist.',
    flags: ['"Guaranteed" returns', "Send-to-receive-more trick", 'Fake scarcity ("first 100")'],
  },
  {
    id: "s4",
    channel: "popup",
    from: "Airdrop Claim",
    isScam: true,
    body: "🎉 You are eligible for a 2,400 TOKEN airdrop! Connect your wallet and approve the transaction to claim before it expires.",
    why: '"Approve" on a shady site can hand over spending permission for your funds. Unexpected airdrops that need approvals are a common drain.',
    flags: ['Unsolicited "you won" prize', "Blind wallet-approve request", "Countdown pressure"],
  },
  {
    id: "s5",
    channel: "email",
    from: "Exchange Security",
    isScam: false,
    body: "A new device signed in to your account. If this was you, no action is needed. If not, reset your password from the app. We never include login links in these alerts.",
    why: "Informational, gives a safe self-serve action, and explicitly avoids embedding a login link. Legitimate.",
    flags: [],
  },
  {
    id: "s6",
    channel: "DM",
    from: "Support Team ✅",
    isScam: true,
    body: "Hi, saw your post about a stuck withdrawal. I can fix it — just share your seed phrase or screen-share and enter it so I can restore your balance.",
    why: "Fake “support” that slides into your DMs after you post a problem. Real support never DMs first or asks for your seed phrase.",
    flags: ["Unsolicited support DM", "Requests seed phrase", "Screen-share to capture keys"],
  },
  {
    id: "s7",
    channel: "popup",
    from: "Trading Bot Pro",
    isScam: true,
    body: "Our AI bot returns 3% DAILY with zero risk. Deposit €250 to activate. Withdraw anytime. Join 40,000 members compounding to millions.",
    why: '"Zero risk" with fixed daily returns is mathematically impossible and a hallmark of Ponzi-style fraud.',
    flags: ['"Zero risk" + fixed daily %', "Deposit-to-activate", "Impossible compounding claim"],
  },
  {
    id: "s8",
    channel: "email",
    from: "Tax Refund Office",
    isScam: true,
    body: "You are owed a €327.50 crypto tax refund. Confirm your exchange login and card details on the linked portal to release payment.",
    why: "Refund bait that harvests your exchange login and card. Authorities do not process refunds through crypto login forms.",
    flags: ["Unexpected refund hook", "Asks for exchange login", "Collects card details"],
  },
  {
    id: "s9",
    channel: "DM",
    from: "Elon (giveaway)",
    isScam: true,
    body: "To celebrate the launch I am giving back! Send any amount of ETH to the address below and it will be returned DOUBLED. Verified event.",
    why: 'The classic celebrity "double your crypto" giveaway. Impersonation + send-to-double is pure theft.',
    flags: ["Celebrity impersonation", "Send-to-double promise", "Irreversible one-way transfer"],
  },
  {
    id: "s10",
    channel: "email",
    from: "Your Broker",
    isScam: false,
    body: "Reminder: your recurring €100 ETF savings-plan buys on the 1st. No action needed. Manage or pause it anytime from your account settings.",
    why: "A routine confirmation of something you set up, with no request and a self-serve way to change it. Legitimate.",
    flags: [],
  },
  {
    id: "s11",
    channel: "popup",
    from: "New Coin Presale",
    isScam: true,
    body: "🚀 Last chance! This coin is about to 100x. Presale ends in 09:58. Buy now before whales pump it — millionaires are being made TODAY.",
    why: '"About to 100x" is a manipulation tactic, not information — price-prediction hype, countdown, and FOMO with no substance.',
    flags: ['Price-prediction hype ("100x")', "Countdown FOMO", '"Buy before it moons" pressure'],
  },
  {
    id: "s12",
    channel: "DM",
    from: "Recruiter — remote job",
    isScam: true,
    body: "Easy remote task: buy crypto with your own money, forward it to our vendor wallet, keep 10%. Start today, paid daily.",
    why: "A money-mule / advance-fee scam dressed as a job. You front real money and are left holding the loss.",
    flags: ['"Use your own money first"', "Forward funds to a stranger", "Too-easy daily pay"],
  },
  {
    id: "s13",
    channel: "email",
    from: "Exchange Newsletter",
    isScam: false,
    body: "This month's education note: what an index fund is, and why fees matter. No action needed — just a read. Unsubscribe anytime.",
    why: "Purely educational, asks for nothing, and offers a clean unsubscribe. This is what a legitimate newsletter looks like.",
    flags: [],
  },
  {
    id: "s14",
    channel: "popup",
    from: "Browser Alert",
    isScam: true,
    body: "⚠️ Your device may be at risk! Your crypto wallet is exposed. Install WalletGuard now and enter your seed phrase to scan for threats.",
    why: "Fake security scare. No tool needs your seed phrase to 'scan' anything — entering it hands over your funds.",
    flags: ["Fake malware scare", "Asks for seed phrase", "Pushes an unknown app"],
  },
  {
    id: "s15",
    channel: "DM",
    from: "Verified ✅ Giveaway Bot",
    isScam: true,
    body: "Congrats! You were selected in our community giveaway. Claim 1 BTC — just pay a small 0.005 BTC 'network release fee' to this address first.",
    why: "The advance-fee trick: pay a small amount to unlock a big 'prize' that never arrives. A blue tick means nothing here.",
    flags: ["Prize you never entered for", '"Release fee" up front', "Fake verified badge"],
  },
  {
    id: "s16",
    channel: "email",
    from: "Your Bank",
    isScam: false,
    body: "We noticed a login from a new device. If this was you, ignore this. If not, call the number on the back of your card. We won't ask for codes here.",
    why: "Directs you to the official number on your card and never requests credentials in the message. Legitimate.",
    flags: [],
  },
  {
    id: "s17",
    channel: "DM",
    from: "Investment Mentor",
    isScam: true,
    body: "I turned €500 into €12,000 in 3 weeks with my private signals group. Only 5 spots left. Send your first deposit and I'll trade it for you.",
    why: "Someone else 'trading it for you' plus guaranteed-sounding returns and false scarcity — a managed-account scam.",
    flags: ["Unrealistic past returns", "Hands your money to a stranger", '"Only 5 spots left"'],
  },
  {
    id: "s18",
    channel: "popup",
    from: "Wallet Connect",
    isScam: true,
    body: "Sync error detected. Re-validate your wallet by entering your 12 or 24-word phrase to restore access. This is 100% secure and encrypted.",
    why: "'Re-validate by entering your phrase' is theft. The word 'secure' in the message doesn't make it so.",
    flags: ["Asks for recovery phrase", "Fake 'sync error'", 'Reassurance theatre ("100% secure")'],
  },
  {
    id: "s19",
    channel: "email",
    from: "Broker Support",
    isScam: false,
    body: "Your withdrawal of €200 to your linked bank account is being processed and should arrive in 1–2 business days. No action required.",
    why: "A neutral status update about something you initiated, requesting nothing. This is normal and safe.",
    flags: [],
  },
  {
    id: "s20",
    channel: "DM",
    from: "Support (they messaged first)",
    isScam: true,
    body: "Hello, this is official support. To resolve your ticket faster, please install AnyDesk so I can remote in and fix your account settings.",
    why: "Real support won't cold-DM you or ask to remote-control your device — screen control lets them drain accounts.",
    flags: ["Unsolicited 'support' DM", "Remote-access request", "Pressure to act fast"],
  },
  {
    id: "s21",
    channel: "popup",
    from: "Token Claim Portal",
    isScam: true,
    body: "Claim your $AIRDROP now! Connect wallet and sign the transaction to receive 5,000 tokens before the pool empties.",
    why: "A blind 'sign' on a shady site can grant permission to move your assets. Unexpected airdrops needing signatures are a drain.",
    flags: ["Unsolicited airdrop", "Blind transaction signature", "Scarcity pressure"],
  },
  {
    id: "s22",
    channel: "email",
    from: "CryptoTax Authority",
    isScam: true,
    body: "FINAL NOTICE: unpaid crypto tax of €412. Pay within 24h via the crypto link below to avoid legal action and account freezing.",
    why: "Tax offices don't demand crypto payments over email with 24-hour threats. Urgency + unusual payment rail = scam.",
    flags: ["Threat + 24h deadline", "Demands crypto payment", "Impersonates an authority"],
  },
  {
    id: "s23",
    channel: "DM",
    from: "Old friend (hacked?)",
    isScam: true,
    body: "Hey!! I made $8k on this new platform, you have to try it. Here's my referral link — use code LUCKY for a bonus. Trust me it's legit!",
    why: "Classic hacked-account or shill pattern: excited testimonial, referral link, a 'bonus' code, zero specifics.",
    flags: ["Too-good testimonial", "Referral-link push", '"Trust me it\'s legit"'],
  },
  {
    id: "s24",
    channel: "email",
    from: "ETF Provider",
    isScam: false,
    body: "Annual document: your fund's costs and charges summary is available in your account. Reading it once a year is a good habit.",
    why: "Points you to your own account for a routine document and asks for nothing. Legitimate and, honestly, worth reading.",
    flags: [],
  },
  {
    id: "s25",
    channel: "popup",
    from: "Live Price Bot",
    isScam: true,
    body: "AI signal: BUY NOW. This coin will pump 40% in the next hour — our model is 99% accurate. Act before the window closes.",
    why: "No model predicts short-term prices with '99% accuracy'. This is FOMO bait to get you buying on cue.",
    flags: ['Price prediction ("40% in an hour")', "Fake accuracy claim", "Countdown pressure"],
  },
  {
    id: "s26",
    channel: "DM",
    from: "Romance / long chat",
    isScam: true,
    body: "I care about your future 💛 My uncle shares a private crypto tip that always wins. Start with €1,000 and we'll grow it together.",
    why: "The 'pig butchering' pattern: warmth and trust built over time, then a can't-lose investment. It's a long-game scam.",
    flags: ["Emotional grooming", '"Always wins" tip', "Pressure to deposit"],
  },
  {
    id: "s27",
    channel: "email",
    from: "Exchange Security",
    isScam: false,
    body: "Two-factor authentication was enabled on your account. If you did this, no action is needed. If not, secure your account from the app.",
    why: "Confirms a security change and points you to the app rather than a link. This is how real alerts behave.",
    flags: [],
  },
  {
    id: "s28",
    channel: "popup",
    from: "Recovery Service",
    isScam: true,
    body: "Lost crypto to a scam? We're licensed fund-recovery experts. Pay a 15% upfront retainer and we'll trace and return your coins.",
    why: "A scam that preys on scam victims. 'Recovery services' with upfront fees are a second theft — irreversible transfers can't be clawed back this way.",
    flags: ["Targets past victims", "Upfront retainer", "Promises the impossible"],
  },
  {
    id: "s29",
    channel: "DM",
    from: "Staking Rewards",
    isScam: true,
    body: "Stake here for a fixed 2% DAILY reward, paid automatically, withdraw anytime. Over 20,000 members earning passively right now.",
    why: "A fixed 2% daily is mathematically impossible to sustain — the signature of a Ponzi that pays early users with new deposits.",
    flags: ['"Fixed daily" reward', "Impossible yield", "Social-proof numbers"],
  },
  {
    id: "s30",
    channel: "email",
    from: "Robo-advisor",
    isScam: false,
    body: "Your portfolio was automatically rebalanced back to your chosen risk level this quarter. Here's a summary — no action needed.",
    why: "A routine, factual update about a service you set up, asking for nothing. Legitimate.",
    flags: [],
  },
  {
    id: "s31",
    channel: "DM",
    from: "Wealth Builders 2026 (group invite)",
    isScam: true,
    body: "You've been added to our private investment group 🔥 Our analyst posts daily entries — members made 300% last month (screenshots pinned). Deposit via our partner platform to unlock VIP signals.",
    why: "Being added to a stranger's 'investment group' is the funnel: staged profit screenshots build trust, then the 'partner platform' swallows your deposit.",
    flags: ["Added to a group you never joined", "Screenshot 'proof' of profits", "Deposit on an unknown partner platform"],
  },
  {
    id: "s32",
    channel: "popup",
    from: "Sponsored Video",
    isScam: true,
    body: "WATCH: beloved TV presenter reveals the trading platform 'banks don't want you to know about'. In the clip he says he doubled his savings in 10 days — start with just €250.",
    why: "AI deepfakes can make any celebrity say anything. Famous-face trading endorsements in ads are almost always fabricated video.",
    flags: ["Celebrity endorsement video (likely deepfake)", '"They don\'t want you to know" framing', "Doubled-in-days claim"],
  },
  {
    id: "s33",
    channel: "email",
    from: "Your Exchange (upgrade team)",
    isScam: true,
    body: "We've upgraded our platform! Log in at exchange-secure-eu.com before Friday to migrate your account — the old site will be shut down and unmigrated balances frozen.",
    why: "Clone-site phishing: real platforms don't move you to a new domain via an emailed link. The 'migration' page just harvests your login.",
    flags: ["Look-alike migration domain", "Login via an emailed link", "Frozen-balance deadline threat"],
  },
  {
    id: "s34",
    channel: "email",
    from: "Your Broker",
    isScam: false,
    body: "Scheduled maintenance this Sunday 02:00–04:00 CET. Trading and withdrawals will be briefly unavailable. No action is needed on your part.",
    why: "A boring, factual heads-up with a specific window and no request. Boring is a good sign.",
    flags: [],
  },
  {
    id: "s35",
    channel: "DM",
    from: "Certified Blockchain Investigator",
    isScam: true,
    body: "I saw your comment about losing crypto to a scam. Our licensed recovery unit traces stolen funds on-chain — we returned €2M to victims last quarter. Pay the case-opening fee and we start today.",
    why: "Recovery agents who DM scam victims are running the second scam. Irreversible transfers cannot be 'traced and returned' for a fee.",
    flags: ["Cold DM after your public complaint", "Upfront case-opening fee", "Promises to reverse irreversible transfers"],
  },
  {
    id: "s36",
    channel: "DM",
    from: "Unknown number",
    isScam: true,
    body: "Hi Anna, is dinner still on for Saturday? ...Oh no, wrong number, so sorry! 😊 You seem friendly though — what do you do? I work in finance in Singapore.",
    why: "The 'wrong number' opener is a scripted start to pig butchering: weeks of warm chat, then a can't-lose investment pitch. The finance mention is the seed.",
    flags: ['Staged "wrong number" from a stranger', "Quick pivot to personal chat", "Unprompted finance-job mention"],
  },
  {
    id: "s37",
    channel: "email",
    from: "Markets Regulator — Enforcement",
    isScam: true,
    body: "Our systems flagged your investment account on a fraud watchlist. Verify your identity and current holdings via the secure portal within 48 hours to avoid suspension.",
    why: "Regulators publish warnings; they don't email individuals demanding holdings via a portal link. This impersonates authority to harvest credentials.",
    flags: ["Impersonates a regulator", "48-hour suspension threat", 'Link to a "secure portal" collecting logins'],
  },
  {
    id: "s38",
    channel: "popup",
    from: "Withdrawal Verification",
    isScam: true,
    body: "One step left: scan this QR code with your banking app to confirm you are a real person and release your pending withdrawal.",
    why: "In a banking app, scanning a QR code typically authorizes a payment. There is no such thing as a QR 'humanity check' — you'd be approving a transfer out.",
    flags: ["QR scan with your banking app", "Withdrawal held hostage", 'Made-up "verification" step'],
  },
  {
    id: "s39",
    channel: "email",
    from: "HR — Remote Careers",
    isScam: true,
    body: "Congratulations, you're hired as a remote crypto analyst at €4,500/month! To activate your trading dashboard, fund it with a fully refundable €300 training deposit.",
    why: "Real employers pay you — they never charge you to start. A 'refundable deposit' for a job you didn't apply to is an advance-fee scam.",
    flags: ["Job offer you never applied for", '"Refundable" deposit up front', "Pay-to-activate dashboard"],
  },
  {
    id: "s40",
    channel: "email",
    from: "Your Exchange (compliance)",
    isScam: false,
    body: "As required under EU crypto-asset rules, a reminder: crypto-assets can lose all their value, are volatile, and are not covered by deposit guarantee schemes. No action needed.",
    why: "Regulated platforms must send sober risk warnings like this. It asks for nothing and sells nothing — that's the point.",
    flags: [],
  },
  {
    id: "s41",
    channel: "DM",
    from: "Pension Review Specialist",
    isScam: true,
    body: "Free pension health check! Your locked pension is underperforming — we can transfer it into a high-growth alternative fund paying a fixed 12% a year. Book your call today.",
    why: "Unsolicited pension-transfer offers are how life savings vanish. 'Fixed 12%' doesn't exist, and moving out of a regulated scheme is usually irreversible.",
    flags: ["Cold contact about your pension", 'Impossible "fixed 12%" yield', "Pushes you out of regulated protection"],
  },
  {
    id: "s42",
    channel: "popup",
    from: "GreenGrid Token",
    isScam: true,
    body: "Energy prices are exploding again — profit from the crisis! Our token pays 2% weekly, backed by real solar farms. Pre-register before public launch.",
    why: "Crisis-themed pitches recycle whatever is in the news. Fixed weekly returns 'backed by' assets you can't verify is Ponzi language with a green coat of paint.",
    flags: ["Rides a news crisis", "Fixed 2% weekly return", "Unverifiable 'backed by solar farms' claim"],
  },
  {
    id: "s43",
    channel: "email",
    from: "National Tax Authority (?)",
    isScam: true,
    body: "Our records show undeclared crypto gains on your file. Settle €693 within 5 days via the crypto payment link below to avoid prosecution and asset freezing.",
    why: "The tax office communicates via official post and your government portal — and never, ever demands payment in crypto. Threat plus odd payment rail = scam.",
    flags: ["Demands payment in crypto", "Prosecution threat + short deadline", "Impersonates the tax authority"],
  },
  {
    id: "s44",
    channel: "email",
    from: "Your Broker",
    isScam: false,
    body: "Your ETF paid a dividend of €3.42, credited to your cash balance today. Details are in your account statement. No action needed.",
    why: "A small, specific, factual notification about your own holding, asking for nothing. Exactly what real dividend mail looks like.",
    flags: [],
  },
  {
    id: "s45",
    channel: "DM",
    from: "Exchange Verification Dept.",
    isScam: true,
    body: "Under new EU rules we must re-verify all accounts. Please join a short video call and share your screen while logged in so we can confirm your balance and settings.",
    why: "Screen-sharing while logged in shows a stranger your balance, settings, and any codes on screen. No verification process on earth works this way.",
    flags: ["Unsolicited 'verification' call", "Screen-share while logged in", "Fake regulatory pretext"],
  },
  {
    id: "s46",
    channel: "email",
    from: "MiCA Compliance Notice",
    isScam: true,
    body: "Deadline alert: your current wallet becomes non-compliant under MiCA on the 30th. Transfer your assets to the compliant wallet address below to retain access.",
    why: "No regulation ever requires sending your coins to someone else's address. 'Compliance transfer' is just theft with legal-sounding wrapping.",
    flags: ["Move-funds-to-their-address demand", "Regulation used as pressure", "Hard deadline"],
  },
  {
    id: "s47",
    channel: "popup",
    from: "Token Received",
    isScam: true,
    body: "You received 940 XREWARD tokens worth €2,100! To swap them for cash, visit xreward-claim.io and approve access to your wallet.",
    why: "Dusting: worthless tokens appear in your wallet with instructions attached. The 'claim' site's approval request is a drainer — ignore surprise tokens entirely.",
    flags: ["Tokens you never bought", "Surprise windfall valuation", "Approve-access request on an unknown site"],
  },
  {
    id: "s48",
    channel: "email",
    from: "Your Exchange",
    isScam: false,
    body: "From 1 September, the trading fee on your plan changes from 0.25% to 0.22% per order. The full fee schedule is available in the app. No action needed.",
    why: "A dated, specific fee-change notice pointing to the app — routine required communication from a real platform.",
    flags: [],
  },
  {
    id: "s49",
    channel: "DM",
    from: "TradeVault Official",
    isScam: true,
    body: "Still deciding? Check our 4.9★ Trustpilot — 2,000 five-star reviews can't be wrong! Deposit today and we'll credit a 50% welcome bonus instantly.",
    why: "Review scores can be bought in bulk, and 'deposit bonuses' often come with terms that block withdrawals until you trade impossible volumes.",
    flags: ["Review score as the only proof", "Deposit bonus bait", "Pressure to decide today"],
  },
  {
    id: "s50",
    channel: "DM",
    from: "Finfluencer post",
    isScam: true,
    body: "New video: 'The ONLY token I'm buying this year 🚀' — I put €50k of my own money in. Link in bio, use my code for a 20% deposit bonus!",
    why: "A promo with a referral code and no ad disclosure is almost certainly paid — the code IS the payment. Undisclosed promotion of a token is the red flag here.",
    flags: ["Referral code with no #ad disclosure", 'Unverifiable "own money" claim', "Single-token hype"],
  },
  {
    id: "s51",
    channel: "email",
    from: "Your Regulator's Consumer Newsletter",
    isScam: false,
    body: "This quarter: how to check a firm's licence in our public register, and new warnings about clone firms. Read online at your convenience — no reply needed.",
    why: "Educational content from a regulator that asks nothing of you and points to public resources. Legitimate — and the register tip is genuinely useful.",
    flags: [],
  },
  {
    id: "s52",
    channel: "popup",
    from: "App Update Required",
    isScam: true,
    body: "Your broker's official app has moved! Download version 2.0 directly from broker-app-update.net — app store versions are outdated and may lose your data.",
    why: "Real apps update through the official app stores, full stop. A side-loaded 'new version' is a clone app built to capture your login.",
    flags: ["Download outside the official store", "Look-alike download domain", "Data-loss scare tactic"],
  },
  {
    id: "s53",
    channel: "popup",
    from: "Your Exchange App",
    isScam: false,
    body: "Security tip: enable two-factor authentication under Settings → Security. Setup happens entirely inside the app — we will never ask for your codes anywhere else.",
    why: "An in-app prompt nudging you toward a genuine security feature, with no link and an explicit warning about codes. This is what good looks like.",
    flags: [],
  },
  {
    id: "s54",
    channel: "popup",
    from: "LIVE Stream Event",
    isScam: true,
    body: "🔴 LIVE NOW: legendary investor is doubling all crypto sent during the stream to thank his fans. 12,000 watching. Event ends when the stream does!",
    why: "Deepfaked or replayed footage of a famous investor plus a send-to-double address — the giveaway livestream is a fully automated theft machine.",
    flags: ["Send-to-double 'giveaway'", "Deepfake/replayed celebrity stream", "Ends-with-stream urgency"],
  },
  {
    id: "s55",
    channel: "DM",
    from: "Finfluencer post",
    isScam: false,
    body: "New video is live: 'How index funds actually work.' Heads-up — this one is sponsored by a broker (#ad, disclosed in the video and description). It's an explainer, no picks, no codes.",
    why: "Sponsored content done by the rules: clear #ad disclosure, no pressure, no bonus codes, no specific picks. Still watch critically, but disclosure is the honest path.",
    flags: [],
  },
  {
    id: "s56",
    channel: "DM",
    from: "Exchange Fraud Team",
    isScam: true,
    body: "URGENT: your account is being drained right now. Move your remaining funds to the temporary safety wallet below while we investigate. Every minute counts.",
    why: "The 'safe account' trick: manufactured panic to make you move money to the thief yourself. Real platforms freeze accounts internally — they never ask you to transfer out.",
    flags: ["Move-to-safety-wallet demand", "Manufactured panic", "Unsolicited 'fraud team' contact"],
  },
  {
    id: "s57",
    channel: "popup",
    from: "Best Brokers 2026",
    isScam: true,
    body: "We compared 50 brokers — our #1 rated 'EU licensed' platform pays a 15% welcome yield on deposits. Leave your phone number for a free consultation with an advisor.",
    why: "Fake comparison sites exist to harvest phone numbers for boiler-room callbacks. A 15% 'welcome yield' on deposits doesn't exist at any licensed firm.",
    flags: ["Phone-number harvesting", "Impossible 15% welcome yield", "Unverifiable licence claim"],
  },
  {
    id: "s58",
    channel: "DM",
    from: "Group Admin (private desk)",
    isScam: true,
    body: "As an active member of our trading group, you qualify for the private arbitrage desk. Minimum €500 entry — profits are guaranteed by smart contract, so there is zero risk.",
    why: "'Guaranteed by smart contract' is technobabble — code can't guarantee profits. Admin-impersonation DMs upsell group members into the real trap.",
    flags: ['"Guaranteed by smart contract" nonsense', "Admin-style DM upsell", "Minimum deposit for a 'private desk'"],
  },
  {
    id: "s59",
    channel: "email",
    from: "Account Services",
    isScam: true,
    body: "Notice: a €50 dormancy fee will be charged to your account this week. To waive it, verify your card details on the form below before midnight today.",
    why: "A surprise fee that vanishes if you hand over card details is a harvesting form, not a waiver. Real fee notices point you to your own account, not a form.",
    flags: ["Card-detail collection form", "Surprise fee out of nowhere", "Midnight deadline"],
  },
  {
    id: "s60",
    channel: "popup",
    from: "EU Green Energy Grant",
    isScam: true,
    body: "Citizens can now claim a €500 green-investment credit under the EU energy programme. Verify eligibility with your bank login on the official-looking portal — closes this week.",
    why: "Governments don't hand out investment credits via popups, and no grant check needs your bank login. Official-sounding branding is doing all the work here.",
    flags: ["Grant you never applied for", "Bank login on an external portal", "Closes-this-week pressure"],
  },
];
