import type { ScamScenario } from "./types";

// Scam-spotting scenarios — teaches Lesson 7 red flags, names no real assets.
export const SCAM_SCENARIOS: ScamScenario[] = [
  {
    id: "s1",
    channel: "DM",
    from: "Wallet Support",
    isScam: true,
    body: "⚠️ Your wallet flagged unusual activity. To secure it, verify your 12-word recovery phrase at wallet-verify-secure.net within 30 minutes or access will be locked.",
    why: "No real service ever needs your recovery phrase — it IS your wallet. Urgency + a look-alike link are classic theft.",
    flags: ["Asks for your recovery phrase", "Manufactured 30-minute urgency", 'Look-alike "verify" domain'],
  },
  {
    id: "s2",
    channel: "email",
    from: "ETF Broker",
    isScam: false,
    body: "Your monthly statement is ready. Log in at your broker directly to view it. We will never ask for your password or 2FA code by email.",
    why: "Neutral, no urgency, asks for nothing, and tells you to navigate to the site yourself. That is how legitimate messages read.",
    flags: [],
  },
  {
    id: "s3",
    channel: "DM",
    from: "CryptoKing_Signals",
    isScam: true,
    body: "Send 0.1 ETH to this address and get 0.5 ETH back — guaranteed, today only. First 100 people. My followers are already 5x up. DM me GO.",
    why: '"Send money, get more back guaranteed" is always a scam. No one gives away free returns; guaranteed multiples do not exist.',
    flags: ['"Guaranteed" returns', "Send-to-receive-more trick", 'Fake scarcity ("first 100")'],
  },
  {
    id: "s4",
    channel: "popup",
    from: "Airdrop Claim",
    isScam: true,
    body: "🎉 You are eligible for a 2,400 TOKEN airdrop! Connect your wallet and approve the transaction to claim before it expires.",
    why: '"Approve" on a shady site can hand over spending permission for your funds. Unexpected airdrops that need approvals are a common drain.',
    flags: ['Unsolicited "you won" prize', "Blind wallet-approve request", "Countdown pressure"],
  },
  {
    id: "s5",
    channel: "email",
    from: "Exchange Security",
    isScam: false,
    body: "A new device signed in to your account. If this was you, no action is needed. If not, reset your password from the app. We never include login links in these alerts.",
    why: "Informational, gives a safe self-serve action, and explicitly avoids embedding a login link. Legitimate.",
    flags: [],
  },
  {
    id: "s6",
    channel: "DM",
    from: "Support Team ✅",
    isScam: true,
    body: "Hi, saw your post about a stuck withdrawal. I can fix it — just share your seed phrase or screen-share and enter it so I can restore your balance.",
    why: "Fake “support” that slides into your DMs after you post a problem. Real support never DMs first or asks for your seed phrase.",
    flags: ["Unsolicited support DM", "Requests seed phrase", "Screen-share to capture keys"],
  },
  {
    id: "s7",
    channel: "popup",
    from: "Trading Bot Pro",
    isScam: true,
    body: "Our AI bot returns 3% DAILY with zero risk. Deposit €250 to activate. Withdraw anytime. Join 40,000 members compounding to millions.",
    why: '"Zero risk" with fixed daily returns is mathematically impossible and a hallmark of Ponzi-style fraud.',
    flags: ['"Zero risk" + fixed daily %', "Deposit-to-activate", "Impossible compounding claim"],
  },
  {
    id: "s8",
    channel: "email",
    from: "Tax Refund Office",
    isScam: true,
    body: "You are owed a €327.50 crypto tax refund. Confirm your exchange login and card details on the linked portal to release payment.",
    why: "Refund bait that harvests your exchange login and card. Authorities do not process refunds through crypto login forms.",
    flags: ["Unexpected refund hook", "Asks for exchange login", "Collects card details"],
  },
  {
    id: "s9",
    channel: "DM",
    from: "Elon (giveaway)",
    isScam: true,
    body: "To celebrate the launch I am giving back! Send any amount of ETH to the address below and it will be returned DOUBLED. Verified event.",
    why: 'The classic celebrity "double your crypto" giveaway. Impersonation + send-to-double is pure theft.',
    flags: ["Celebrity impersonation", "Send-to-double promise", "Irreversible one-way transfer"],
  },
  {
    id: "s10",
    channel: "email",
    from: "Your Broker",
    isScam: false,
    body: "Reminder: your recurring €100 ETF savings-plan buys on the 1st. No action needed. Manage or pause it anytime from your account settings.",
    why: "A routine confirmation of something you set up, with no request and a self-serve way to change it. Legitimate.",
    flags: [],
  },
  {
    id: "s11",
    channel: "popup",
    from: "New Coin Presale",
    isScam: true,
    body: "🚀 Last chance! This coin is about to 100x. Presale ends in 09:58. Buy now before whales pump it — millionaires are being made TODAY.",
    why: '"About to 100x" is a manipulation tactic, not information — price-prediction hype, countdown, and FOMO with no substance.',
    flags: ['Price-prediction hype ("100x")', "Countdown FOMO", '"Buy before it moons" pressure'],
  },
  {
    id: "s12",
    channel: "DM",
    from: "Recruiter — remote job",
    isScam: true,
    body: "Easy remote task: buy crypto with your own money, forward it to our vendor wallet, keep 10%. Start today, paid daily.",
    why: "A money-mule / advance-fee scam dressed as a job. You front real money and are left holding the loss.",
    flags: ['"Use your own money first"', "Forward funds to a stranger", "Too-easy daily pay"],
  },
  {
    id: "s13",
    channel: "email",
    from: "Exchange Newsletter",
    isScam: false,
    body: "This month's education note: what an index fund is, and why fees matter. No action needed — just a read. Unsubscribe anytime.",
    why: "Purely educational, asks for nothing, and offers a clean unsubscribe. This is what a legitimate newsletter looks like.",
    flags: [],
  },
  {
    id: "s14",
    channel: "popup",
    from: "Browser Alert",
    isScam: true,
    body: "⚠️ Your device may be at risk! Your crypto wallet is exposed. Install WalletGuard now and enter your seed phrase to scan for threats.",
    why: "Fake security scare. No tool needs your seed phrase to 'scan' anything — entering it hands over your funds.",
    flags: ["Fake malware scare", "Asks for seed phrase", "Pushes an unknown app"],
  },
  {
    id: "s15",
    channel: "DM",
    from: "Verified ✅ Giveaway Bot",
    isScam: true,
    body: "Congrats! You were selected in our community giveaway. Claim 1 BTC — just pay a small 0.005 BTC 'network release fee' to this address first.",
    why: "The advance-fee trick: pay a small amount to unlock a big 'prize' that never arrives. A blue tick means nothing here.",
    flags: ["Prize you never entered for", '"Release fee" up front', "Fake verified badge"],
  },
  {
    id: "s16",
    channel: "email",
    from: "Your Bank",
    isScam: false,
    body: "We noticed a login from a new device. If this was you, ignore this. If not, call the number on the back of your card. We won't ask for codes here.",
    why: "Directs you to the official number on your card and never requests credentials in the message. Legitimate.",
    flags: [],
  },
  {
    id: "s17",
    channel: "DM",
    from: "Investment Mentor",
    isScam: true,
    body: "I turned €500 into €12,000 in 3 weeks with my private signals group. Only 5 spots left. Send your first deposit and I'll trade it for you.",
    why: "Someone else 'trading it for you' plus guaranteed-sounding returns and false scarcity — a managed-account scam.",
    flags: ["Unrealistic past returns", "Hands your money to a stranger", '"Only 5 spots left"'],
  },
  {
    id: "s18",
    channel: "popup",
    from: "Wallet Connect",
    isScam: true,
    body: "Sync error detected. Re-validate your wallet by entering your 12 or 24-word phrase to restore access. This is 100% secure and encrypted.",
    why: "'Re-validate by entering your phrase' is theft. The word 'secure' in the message doesn't make it so.",
    flags: ["Asks for recovery phrase", "Fake 'sync error'", 'Reassurance theatre ("100% secure")'],
  },
  {
    id: "s19",
    channel: "email",
    from: "Broker Support",
    isScam: false,
    body: "Your withdrawal of €200 to your linked bank account is being processed and should arrive in 1–2 business days. No action required.",
    why: "A neutral status update about something you initiated, requesting nothing. This is normal and safe.",
    flags: [],
  },
  {
    id: "s20",
    channel: "DM",
    from: "Support (they messaged first)",
    isScam: true,
    body: "Hello, this is official support. To resolve your ticket faster, please install AnyDesk so I can remote in and fix your account settings.",
    why: "Real support won't cold-DM you or ask to remote-control your device — screen control lets them drain accounts.",
    flags: ["Unsolicited 'support' DM", "Remote-access request", "Pressure to act fast"],
  },
  {
    id: "s21",
    channel: "popup",
    from: "Token Claim Portal",
    isScam: true,
    body: "Claim your $AIRDROP now! Connect wallet and sign the transaction to receive 5,000 tokens before the pool empties.",
    why: "A blind 'sign' on a shady site can grant permission to move your assets. Unexpected airdrops needing signatures are a drain.",
    flags: ["Unsolicited airdrop", "Blind transaction signature", "Scarcity pressure"],
  },
  {
    id: "s22",
    channel: "email",
    from: "CryptoTax Authority",
    isScam: true,
    body: "FINAL NOTICE: unpaid crypto tax of €412. Pay within 24h via the crypto link below to avoid legal action and account freezing.",
    why: "Tax offices don't demand crypto payments over email with 24-hour threats. Urgency + unusual payment rail = scam.",
    flags: ["Threat + 24h deadline", "Demands crypto payment", "Impersonates an authority"],
  },
  {
    id: "s23",
    channel: "DM",
    from: "Old friend (hacked?)",
    isScam: true,
    body: "Hey!! I made $8k on this new platform, you have to try it. Here's my referral link — use code LUCKY for a bonus. Trust me it's legit!",
    why: "Classic hacked-account or shill pattern: excited testimonial, referral link, a 'bonus' code, zero specifics.",
    flags: ["Too-good testimonial", "Referral-link push", '"Trust me it\'s legit"'],
  },
  {
    id: "s24",
    channel: "email",
    from: "ETF Provider",
    isScam: false,
    body: "Annual document: your fund's costs and charges summary is available in your account. Reading it once a year is a good habit.",
    why: "Points you to your own account for a routine document and asks for nothing. Legitimate and, honestly, worth reading.",
    flags: [],
  },
  {
    id: "s25",
    channel: "popup",
    from: "Live Price Bot",
    isScam: true,
    body: "AI signal: BUY NOW. This coin will pump 40% in the next hour — our model is 99% accurate. Act before the window closes.",
    why: "No model predicts short-term prices with '99% accuracy'. This is FOMO bait to get you buying on cue.",
    flags: ['Price prediction ("40% in an hour")', "Fake accuracy claim", "Countdown pressure"],
  },
  {
    id: "s26",
    channel: "DM",
    from: "Romance / long chat",
    isScam: true,
    body: "I care about your future 💛 My uncle shares a private crypto tip that always wins. Start with €1,000 and we'll grow it together.",
    why: "The 'pig butchering' pattern: warmth and trust built over time, then a can't-lose investment. It's a long-game scam.",
    flags: ["Emotional grooming", '"Always wins" tip', "Pressure to deposit"],
  },
  {
    id: "s27",
    channel: "email",
    from: "Exchange Security",
    isScam: false,
    body: "Two-factor authentication was enabled on your account. If you did this, no action is needed. If not, secure your account from the app.",
    why: "Confirms a security change and points you to the app rather than a link. This is how real alerts behave.",
    flags: [],
  },
  {
    id: "s28",
    channel: "popup",
    from: "Recovery Service",
    isScam: true,
    body: "Lost crypto to a scam? We're licensed fund-recovery experts. Pay a 15% upfront retainer and we'll trace and return your coins.",
    why: "A scam that preys on scam victims. 'Recovery services' with upfront fees are a second theft — irreversible transfers can't be clawed back this way.",
    flags: ["Targets past victims", "Upfront retainer", "Promises the impossible"],
  },
  {
    id: "s29",
    channel: "DM",
    from: "Staking Rewards",
    isScam: true,
    body: "Stake here for a fixed 2% DAILY reward, paid automatically, withdraw anytime. Over 20,000 members earning passively right now.",
    why: "A fixed 2% daily is mathematically impossible to sustain — the signature of a Ponzi that pays early users with new deposits.",
    flags: ['"Fixed daily" reward', "Impossible yield", "Social-proof numbers"],
  },
  {
    id: "s30",
    channel: "email",
    from: "Robo-advisor",
    isScam: false,
    body: "Your portfolio was automatically rebalanced back to your chosen risk level this quarter. Here's a summary — no action needed.",
    why: "A routine, factual update about a service you set up, asking for nothing. Legitimate.",
    flags: [],
  },
];
