import type { WeeklyItem } from "./types";

// Rotated deterministically by ISO week (see this-week-card). No market calls,
// no predictions, just a fresh, evergreen nudge each week to keep the habit alive.
export const WEEKLY_ITEMS: WeeklyItem[] = [
  {
    id: "w1",
    kind: "concept",
    title: "Time in the market",
    body: "The biggest lever isn't picking the perfect investment, it's starting early and giving compounding years to work. Boring and consistent beats clever and sporadic.",
  },
  {
    id: "w2",
    kind: "myth",
    title: "Myth: you need a lot of money to start",
    body: "Many regulated brokers let you buy fractional shares and start with small recurring amounts. The habit matters more than the size of the first buy.",
  },
  {
    id: "w3",
    kind: "tip",
    title: "Check less, not more",
    body: "Frequent checking tends to trigger emotional, ill-timed decisions. Set a boring schedule and let it run, most days there's nothing you need to do.",
  },
  {
    id: "w4",
    kind: "concept",
    title: "Volatility vs. permanent loss",
    body: "A broad market falling and recovering is volatility, noise for a long-term investor. Permanent loss is a single thing going to zero, or panic-selling at the bottom.",
  },
  {
    id: "w5",
    kind: "myth",
    title: "Myth: fees are too small to matter",
    body: "0.2% vs 1.5% a year feels tiny, but over decades it can quietly cost you a third of your final pot. Small percentages compound, against you, too.",
  },
  {
    id: "w6",
    kind: "tip",
    title: "Decide the crypto slice once",
    body: "If you hold any, size it in the cold light of day as an amount you could lose entirely, then don't top it up in a hype frenzy.",
  },
  {
    id: "w7",
    kind: "concept",
    title: "Diversification, the free lunch",
    body: "Own hundreds of companies and one going bust barely registers; own one and it can wipe you out. Spreading risk historically costs very little growth.",
  },
  {
    id: "w8",
    kind: "tip",
    title: "The recovery-phrase rule",
    body: "Your recovery phrase IS your wallet. No legitimate service ever asks for it. Never type it into a website or share it with 'support'.",
  },
  {
    id: "w9",
    kind: "myth",
    title: "Myth: the pros reliably beat the market",
    body: "Most active stock-pickers don't beat a broad, low-cost index over the long run, which is why 'just buy the index' is such common advice.",
  },
  {
    id: "w10",
    kind: "concept",
    title: "Core and satellite",
    body: "A boring diversified core does the long-term work; a small, bounded satellite adds engagement without risking the plan. Your type just leans the shape one way or another.",
  },
  {
    id: "w11",
    kind: "tip",
    title: "Clear expensive debt first",
    body: "Paying off a credit card charging 16% is the one guaranteed 'return' that exists. No sensible investment reliably beats it, clear it, then invest.",
  },
  {
    id: "w12",
    kind: "concept",
    title: "The emergency fund's real job",
    body: "It isn't there to grow. It's there so a broken laptop or a job gap never forces you to sell investments at the worst possible moment.",
  },
  {
    id: "w13",
    kind: "tip",
    title: "Pay yourself first",
    body: "Move a fixed amount to savings or investing the day salary lands, before you can spend it. 'Whatever is left at month's end' is usually nothing.",
  },
  {
    id: "w14",
    kind: "concept",
    title: "Losses hurt double",
    body: "Losing €100 feels about twice as strong as winning €100 feels good. Knowing that wiring exists is half the defence against panic-selling.",
  },
  {
    id: "w15",
    kind: "myth",
    title: "Myth: the winners you see online are the typical outcome",
    body: "Winners post screenshots; the thousands who bought late stay quiet. Survivorship bias makes long-shot bets look far safer than they are.",
  },
  {
    id: "w16",
    kind: "tip",
    title: "Urgency is the tell",
    body: "Countdowns, 'last chance', deadline pressure, long-term investing has no deadline. Only sellers need you to hurry.",
  },
  {
    id: "w17",
    kind: "myth",
    title: "Myth: it was €80, so €50 is a bargain",
    body: "An old price isn't evidence of value, that's anchoring. Things that fall often fall further; the only question is whether it's worth owning today.",
  },
  {
    id: "w18",
    kind: "concept",
    title: "Savings rate beats returns",
    body: "Saving more grows your pot faster AND proves you need a smaller one. It's the strongest lever on the road to financial independence, and the only one you fully control.",
  },
  {
    id: "w19",
    kind: "concept",
    title: "25× your spending",
    body: "A rough financial-independence ballpark: about 25 times your yearly spending. Notice it's spending, not salary, that sets the goalposts.",
  },
  {
    id: "w20",
    kind: "myth",
    title: "Myth: property only goes up",
    body: "After 2008, house prices fell 20–30%+ across several European countries and took years to recover. Real estate cycles like everything else, bricks aren't sacred.",
  },
  {
    id: "w21",
    kind: "concept",
    title: "Real estate without the tenants",
    body: "A REIT ETF spreads you across hundreds of buildings for the price of one share, liquid and diversified, though it still swings with the stock market.",
  },
  {
    id: "w22",
    kind: "tip",
    title: "Test the backup before it matters",
    body: "If you self-custody crypto: restore your wallet from the written phrase before sending real money. An untested backup is a hope, not a backup.",
  },
  {
    id: "w23",
    kind: "concept",
    title: "Yield is payment for risk",
    body: "Every crypto 'earn' percentage has a source: lock-ups, slashing, lending, platform failure. If you can't name the risk, you are the risk.",
  },
  {
    id: "w24",
    kind: "myth",
    title: "Myth: a licensed platform means risk-free products",
    body: "MiCA licensing covers how a platform operates, not the risk inside its yield products. And crypto has no deposit-guarantee scheme.",
  },
  {
    id: "w25",
    kind: "tip",
    title: "Write the note before the storm",
    body: "In calm weather, write down why you invested the way you did. In the next 20% drop, that note will beat your instincts.",
  },
  {
    id: "w26",
    kind: "concept",
    title: "Bear markets are a feature",
    body: "A 20%+ drop arrives every few years on average. For a long-term diversified investor with an emergency fund, it's weather, not the end of the plan.",
  },
];
